# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: reg.docker.eccl/yun/maven-for-eccl:v1.0.1

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--insecure-registry", "reg.docker.eccl", "--registry-mirror", "http://69f0e392.m.daocloud.io"]

stages:
  - buildjar
  - buildimage

cache:
  paths:
    - target/

buildjar:
  tags:
    - buildimage
  only:
    - tags
  stage: buildjar
  script:
    - mvn versions:set -DnewVersion=$CI_COMMIT_TAG
    - mvn package -Dmaven.test.skip=true
    - cp target/cloud-demo-$CI_COMMIT_TAG.jar target/app.jar


buildimage:
  tags:
    - buildimage
  only:
    - tags
  image: docker:stable
  stage: buildimage
  script:
    - docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD reg.docker.eccl
    - docker build -t reg.docker.eccl/dingzhou-xczy/cloud-demo:$CI_COMMIT_TAG .
    - docker push reg.docker.eccl/dingzhou-xczy/cloud-demo:$CI_COMMIT_TAG
